"""
This is the scripts for loading the experiment I-V and EQE generated by bun-ko-kei-ki,
the I-V measurement equipment at TTI

Kan-Hua Lee
"""

import numpy as np
import csv
from pypvcell.spectrum import Spectrum

def readiv(datafile):

    fileobj = open(datafile, 'r')
    csvobj = csv.reader(fileobj)

    # determent the file type
    meastype = next(csvobj);

    if meastype[1].find("I/V") >= 0:
        startDataRow = 28;
        colNameRow = 27;
    xlist = list()
    ylist = list()

    for rownum, row in enumerate(csvobj):
        if rownum == colNameRow:
            xColName = str.rstrip(row[0])
            yColName = str.rstrip(row[1])

        if rownum >= startDataRow:
            xlist.append(float(row[0]))
            ylist.append(float(row[1]))

    xarr = np.array(xlist)
    yarr = np.array(ylist)

    return xarr, yarr, xColName, yColName


def readeqe(datafile):
    fileobj = open(datafile, 'r')
    csvobj = csv.reader(fileobj)

    # determent the file type
    meastype = next(csvobj);

    startDataRow = 29;
    colNameRow = 27;

    xlist = list()
    ylist = list()

    for rownum, row in enumerate(csvobj):
        if rownum == colNameRow:
            xColName = str.rstrip(row[0])
            yColName = str.rstrip(row[1])

        if rownum >= startDataRow:
            xlist.append(float(row[0]))
            ylist.append(float(row[1]))

    xarr = np.array(xlist)
    yarr = np.array(ylist)

    return xarr, yarr, xColName, yColName

def read_qe_sp(fname):

    x,y,_,_=readeqe(fname)

    return Spectrum(x,y,x_unit='nm')


